name: All Builds
on:
  push:
    branches: [ master ]
    tags: 
      - "v*"
  workflow_dispatch:

# Global Settings
env:
  PROJECT_FOLDER: .
  TARGET_PATH: demo/addons/godot_leveldb/bin/
  TARGET_NAME: libgdleveldb
  SCONS_CACHE: ${{ github.workspace }}/.scons-cache/

jobs:
  build:
    runs-on: ${{ matrix.build.os }}
    name: ${{ matrix.build.platform }} - ${{ matrix.target == 'template_debug' && 'Debug' || 'Release' }}
    strategy:
      fail-fast: false
      matrix:
        target: [template_debug, template_release]
        # TODO Add Android build
        build:
          - os: ubuntu-22.04
            platform: linux
            artifact-extension: so
            cache-name: linux-x86_64
          - os: windows-latest
            platform: windows
            artifact-extension: dll
            cache-name: win-x86_64-msvc
          - os: macos-latest
            platform: macos
            artifact-extension: framework
            cache-name: macos-universal
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.build.cache-name }}-${{ matrix.target }}
        continue-on-error: true

      # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Setup Target directory and Compile Snappy (Windows)
        if: runner.os == 'Windows'
        run: |
          if(-Not (Test-Path -Path ${{ env.PROJECT_FOLDER }}\${{ env.TARGET_PATH }}))
          {
            mkdir ${{ env.PROJECT_FOLDER }}\${{ env.TARGET_PATH }}
          }
          cd ${{ env.PROJECT_FOLDER }}/src/snappy/
          git submodule update --init
          mkdir build
          cd build
          cmake ../ -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DSNAPPY_BUILD_TESTS=OFF -DSNAPPY_BUILD_BENCHMARKS=OFF -DSNAPPY_INSTALL=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE="/MT"
          cmake --build . --config Release

      - name: Setup Target directory and Compile Snappy
        if: runner.os != 'Windows'
        run: |
          mkdir -v -p ${{ env.PROJECT_FOLDER }}/${{ env.TARGET_PATH }}
          cd ${{ env.PROJECT_FOLDER }}/src/snappy/
          git submodule update --init
          mkdir build
          cd build
          cmake ../ -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DSNAPPY_BUILD_TESTS=OFF -DSNAPPY_BUILD_BENCHMARKS=OFF -DSNAPPY_INSTALL=OFF
          make

      - name: Compilation
        run: |
          cd ${{ env.PROJECT_FOLDER }}
          scons platform=${{ matrix.build.platform }} target=${{ matrix.target }} target_path=${{ env.TARGET_PATH }} target_name=${{ env.TARGET_NAME }} -j6 ${{ matrix.build.flags }}

      - name: Save Godot build cache
        uses: ./godot-cpp/.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.build.cache-name }}-${{ matrix.target }}
        continue-on-error: true

      - name: Upload Artifact
        env:
          ARTIFACT_FOLDER: ${{ env.PROJECT_FOLDER }}/${{ env.TARGET_PATH }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.cache-name }}-${{ matrix.target }}
          path: ${{ env.ARTIFACT_FOLDER }}*.${{ matrix.build.artifact-extension }}
          if-no-files-found: error
  release:
    name: "Release"
    runs-on: "ubuntu-22.04"
    needs: [build]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Download Artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy Artifacts to bin/-folder
        run: |
          mkdir -v -p ${{ env.PROJECT_FOLDER }}/${{ env.TARGET_PATH }}
          cd ${{ env.PROJECT_FOLDER }}
          cp -r ${{steps.download.outputs.download-path}}/**/* ${{ env.TARGET_PATH }}
          zip -r demo.zip demo/
          cd ${{ env.TARGET_PATH }}/../../..
          zip -r godot_leveldb_${{ github.ref_name }}.zip addons/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ env.PROJECT_FOLDER }}/.github/workflows/release_template.md
          files: |
            ${{ env.PROJECT_FOLDER }}/demo.zip
            ${{ env.PROJECT_FOLDER }}/${{ env.TARGET_PATH }}/../../../godot_leveldb_${{ github.ref_name }}.zip
          draft: true
          prerelease: true


    
